baseURL = "https://simakis.me"
languageCode = "en-us"
title = "Panagiotis Simakis"
theme = "cactus"
copyright = "Panagiotis Simakis" # cactus will use title if copyright is not set
disqusShortname = "simakis-me" # Used when comments is enabled. Cactus will use site title if not set
image = ""
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Curriculum Vitae"
url = "/cv"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Hi there 👋 and welcome to my personal website. I'm a Software Engineer, passionate with NLP and GNU/Linux addict. "
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/sp1thas" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/sp1thas"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/sp1thas"
  [[params.social]]
    name = "linkedin"
    link = "https://linkedin.com/in/psimakis"
  [[params.social]]
    name = "kaggle"
    link = "https://kaggle.com/sp1thas"
  [[params.social]]
    name = "stack-overflow"
    link = "https://stackoverflow.com/users/6779252/panagiotis-simakis"
  [[params.social]]
    name = "stack-exchange"
    link = "https://stackexchange.com/users/9110235/panagiotis-simakis"
  [[params.social]]
    name = "keybase"
    link = "https://keybase.io/spithas"
  [[params.social]]
    name = "dev"
    link = "https://dev.to/sp1thas"
